#pragma once

#include "core/cloud_cover.h"

// GENERATED by scripts/cloud_fit.py -- do not edit by hand.
//
// Fitted from backups/telemetry.sqlite, key 'luminosity', on
// 7 day(s): 2026-08-28 .. 2026-09-03 (8257 readings, UTC-3).
//
// THIS TABLE DESCRIBES ONE SENSOR AT ONE MOUNTING IN ONE SEASON.
// Moving the sensor, shading it, replacing the LDR or letting the
// season move under it all invalidate it, and nothing on the device
// can detect that it has happened. Re-run the fit; the regime table
// it prints is what makes a mounting change visible.
//
// Envelope: 144 bins x 10 min, 0.98 quantile, one (1,2,1) pass.
// Peak 95.88 %, daylight window 07:40..17:39 local.
//
// Hundredths of a percent of full scale, indexed by minute_of_day / 10.
static const uint16_t g_clearSkyTable[144] = {
      544,   694,   749,   409,   180,   471,   761,   761,   762,   474,   186,   445,  // 00:00
      906,   838,   356,   160,   177,   167,   152,   150,   152,   155,   158,   160,  // 02:00
      164,   167,   168,   167,   160,   147,   143,   108,    36,     0,     0,     0,  // 04:00
        0,    40,   236,   592,   968,  1282,  1510,  1723,  2034,  2341,  2460,  2432,  // 06:00
     2611,  3032,  3289,  3468,  3715,  3730,  3435,  3169,  3221,  3458,  3735,  3992,  // 08:00
     4180,  4369,  4520,  4778,  5186,  5447,  5607,  5743,  5857,  5981,  6077,  6132,  // 10:00
     6163,  6238,  6353,  6159,  5737,  5718,  5864,  5969,  6245,  6444,  6562,  6735,  // 12:00
     6891,  7026,  7220,  8016,  8966,  9083,  9160,  9506,  9588,  9342,  8725,  8080,  // 14:00
     7736,  7515,  7214,  6912,  6727,  6601,  6418,  6112,  5227,  3658,  2312,  1495,  // 16:00
      839,   372,   374,   713,   706,   342,   378,   915,  1335,  1410,  1370,  1345,  // 18:00
     1331,  1326,  1326,  1328,  1329,  1329,  1328,  1327,  1327,  1212,   812,   353,  // 20:00
      175,   171,   177,   183,   178,   172,   176,   181,   177,   199,   353,   520,  // 22:00
};

static const CloudModelParams g_cloudParams = {
    g_clearSkyTable,
    144, 10,
    460, 1059,
    0.50f, 0.85f, 0.05f, 0.30f, 5,
    0.30f, 0.070f, 0.035f, 3,
};
